export const initialPosts = [
  {
    id: 'p101',
    gameId: 'destiny-2',
    authorId: 'u002',
    title: 'Need 2 for Crota checkpoint + pinnacles',
    description: 'Chill but focused run, mic preferred. We can explain mechanics if needed.',
    tags: ['chill', 'pve', 'mic-on'],
    neededPlayers: 2,
    createdAt: '2026-04-02T20:41:00Z',
    votes: 19,
    comments: 6,
    reposts: 2,
  },
  {
    id: 'p102',
    gameId: 'apex-legends',
    authorId: 'u003',
    title: 'Ranked grind to Diamond tonight',
    description: 'Need one support main for ranked sessions tonight. Rotations + comms.',
    tags: ['ranked', 'late-night', 'serious'],
    neededPlayers: 1,
    createdAt: '2026-04-03T00:22:00Z',
    votes: 27,
    comments: 11,
    reposts: 3,
  },
  {
    id: 'p103',
    gameId: 'helldivers-2',
    authorId: 'u004',
    title: 'LF3 for bug planets, difficulty 8',
    description: 'New divers welcome. Bring anti-heavy and we rotate stratagem roles.',
    tags: ['teaching', 'pve', 'friendly'],
    neededPlayers: 3,
    createdAt: '2026-04-01T18:00:00Z',
    votes: 45,
    comments: 18,
    reposts: 7,
  },
];