export const currentUser = {
  id: 'u001',
  displayName: 'KaiPilot',
  avatar: 'KP',
  bio: 'Flexible caller for raids, ranked, and chill late-night sessions.',
  timezone: 'UTC-5',
  reputation: 4.8,
  completedSquads: 132,
  friends: ['u002', 'u003'],
  platforms: {
    steam: 'KaiPilot#4412',
    xbox: 'KaiPilot',
    playstation: 'Kai_Pilot',
    discord: 'kai.pilot',
  },
};

export const users = [
  currentUser,
  {
    id: 'u002',
    displayName: 'NovaHex',
    avatar: 'NH',
    bio: 'Objective-focused support main. No toxicity, lots of comms.',
    timezone: 'UTC-8',
    reputation: 4.9,
    completedSquads: 201,
    platforms: {
      steam: 'NovaHex',
      xbox: 'NovaHexX',
      playstation: 'NovaHex',
      discord: 'novahex',
    },
  },
  {
    id: 'u003',
    displayName: 'CipherWisp',
    avatar: 'CW',
    bio: 'IGL for ranked pushes and tournament scrims.',
    timezone: 'UTC+1',
    reputation: 4.7,
    completedSquads: 164,
    platforms: {
      steam: 'CipherWisp',
      xbox: 'CipherWisp77',
      playstation: 'CipherWisp',
      discord: 'cipherwisp',
    },
  },
  {
    id: 'u004',
    displayName: 'RookSignal',
    avatar: 'RS',
    bio: 'Patient raid teacher. Great for first clears.',
    timezone: 'UTC+0',
    reputation: 4.9,
    completedSquads: 320,
    platforms: {
      steam: 'RookSignal',
      xbox: 'RookSignal',
      playstation: 'RookSignal_1',
      discord: 'rooksignal',
    },
  },
];
